### ISSUE TITLE
message added to queue but nothing in list/popup

### ISSUE THREAD

**Issue by sheepdestroyer** [robbielj/chrome-aria2-integration#1]
I have version 1.5.5 from market on chrome 35 / fedora and aria2 1.8.2
when trying to use the extension i get the message download has been sent to the queue but nothing more. no download happens and popup from extention's icon stays empty.

**Comment by robbielj** [comment]
Now aria2 version requirement has been relaxed to 1.15.2+.

**Comment by sheepdestroyer** [comment]
Hi,
I tried again today with self compiled today's git of aria2 : 1.8.5git (my distro's repo only provides up to 1.8.2) and version 1.6.0 of your plugin from the webstore.

my pb is still the same, I get the message download added to queue but nothing else happens. popup still empty

**Comment by robbielj** [comment]
You are sure it is 1.18.5 not 1.8.5? 1.18.5 should work. 
Have a check: set both rpc-listen-all and rpc-allow-origin-all to True, and input the right value of rpc-user/rpc-passwd/rpc-secret in extension setting.
